export default {
    mobiledisplay: [
    {
        id:1,
        imgsrc: '/images/Realme/pro.JPG',
        name: "RealMe",
        model: "Pro6",
        price: 15000,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"5000"

    },
    {
        id:2,
        imgsrc: '/images/Realme/Six.JPG',
        name: "RealMe",
        model: "6S",
        price: 12000,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"5000"
    },
    {
        id:3,
        imgsrc: '/images/Realme/c3i.JPG',
        name: "RealMe",
        model: "C3i",
        price: 8999,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"6000"
    },
    {
        id:4,
        imgsrc: '/images/Realme/c11.JPG',
        name: "RealMe",
        model: "C11",
        price: 8999,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"4500"
    },
    {
        id:5,
        imgsrc: '/images/Realme/Narzo.JPG',
        name: "RealMe",
        model: "Narzo",
        price: 8999,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"5000"
    },
    
    {
        id:6,
        imgsrc: '/images/Samsung/a51.JPG',
        name: "Samsung",
        model: "A51",
        price: 15000,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"7000"

    },
    {
        id:7,
        imgsrc: '/images/Samsung/m11.JPG',
        name: "Samsung",
        model: "M11",
        price: 9000,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"6000"
    },
    {
        id:8,
        imgsrc: '/images/Samsung/m21.JPG',
        name: "Samsung",
        model: "M21",
        price: 11000,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"7000"
    },
    {
        id:9,
        imgsrc: '/images/Oppo/a31.JPG',
        name: "Oppo",
        model: "A31",
        price: 7000,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"4500"
    },
    {
        id:10,
        imgsrc: '/images/Oppo/a92.JPG',
        name: "Oppo",
        model: "A92",
        price: 11999,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"5000"
    },
    {
        id:11,
        imgsrc: '/images/Vivo/V17.JPG',
        name: "Vivo",
        model: "V17",
        price: 15000,
        ram: "4GB",
        rom: "64GB",
        processor: "745 Snapdragon",
        fcam: "16mp",
        bcam: "32mp,2mp for depth",
        colorvariant: "blue,black available",
        protection: "gorilla glass5",
        battery:"4500"
    },
    
    ]
}