export const  MOBILES_LIST_REQUEST = ' MOBILES_LIST_REQUEST';
export const  MOBILES_LIST_SUCCESS = ' MOBILES_LIST_SUCCESS';
export const  MOBILES_LIST_FAIL = ' MOBILES_LIST_FAIL';

export const MOBILES_BRAND_REQUEST = 'MOBILES_BRAND_REQUEST';
export const MOBILES_BRAND_SUCCESS = 'MOBILES_BRAND_SUCCESS';
export const MOBILES_BRAND_FAIL = 'MOBILES_BRAND_FAIL';

