export const MOBILE_LIST_REQUEST = 'MOBILE_LIST_REQUEST';
export const MOBILE_LIST_SUCCESS = 'MOBILE_LIST_SUCCESS';
export const MOBILE_LIST_FAIL = 'MOBILE_LIST_FAIL';

export const MOBILE_DETAILS_REQUEST = 'MOBILE_DETAILS_REQUEST';
export const MOBILE_DETAILS_SUCCESS = 'MOBILE_DETAILS_SUCCESS';
export const MOBILE_DETAILS_FAIL = 'MOBILE_DETAILS_FAIL';

export const BRAND_LIST_REQUEST = 'BRAND_LIST_REQUEST';
export const BRAND_LIST_SUCCESS = 'BRAND_LIST_SUCCESS';
export const BRAND_LIST_FAIL = 'BRAND_LIST_FAIL';